### ISSUE TITLE
negative numbers and almost all apps reset to 0 installs

### ISSUE THREAD

**Issue by theofficialgman** [Botspot/pi-apps-analytics#4]
![image](https://user-images.githubusercontent.com/28281419/142093760-446fefc5-b491-4504-94f2-1f9464296c1b.png)
starting with this commit: https://github.com/Botspot/pi-apps-analytics/commit/7a4039cdb0dfd66c43712ef4a18b944e01aa9ca4

**Comment by Botspot** [comment]
Weird. I'm running the script again.

**Comment by Botspot** [comment]
Okay it seems to have worked this time.

**Comment by theofficialgman** [comment]
@Botspot I'm not convinced its working correctly still
many apps increased their numbers by 30,000 from 2 days ago even when their numbers haven't been increasing much/at all before (when the last correct update was issued)

here were the last good numbers:
```
157017 Minecraft Java
108364 Box86
104575 Discord
86389 Zoom
84655 Wine (x86)
83480 CommanderPi
75706 Minecraft Bedrock
73935 Minecraft Pi (Modded)
71124 Pi Power Tools
69337 Conky
67790 Chromium Widevine
66742 Steam
63272 BalenaEtcher
61590 piKiss
53697 All Is Well
51034 Visual Studio Code
50742 Doom 3
50519 Windows 10 Theme
49471 Snap Store
41556 Update Buddy
```

and these are numbers now:
```
182997 Minecraft Java
134006 Box86
122361 Discord
104991 Wine (x86)
99597 Zoom
97349 CommanderPi
90382 Minecraft Pi (Modded)
88273 Minecraft Bedrock
82765 Pi Power Tools
80861 Conky
79174 Chromium Widevine
77558 Steam
74814 BalenaEtcher
71723 piKiss
62479 All Is Well
60648 Snap Store
59944 Doom 3
59448 Visual Studio Code
58576 Windows 10 Theme
48493 Arduino
48224 Update Buddy
```

notice how those top few increased by over 10K, when previously they were only increasing by about 100-200 every day or two
